services:
  web:
    container_name: web
    build: ./api
    ports:
      - "7020:7020"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./api:/app

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis

  worker:
    build:
      context: ./api
    hostname: worker
    entrypoint: [ "celery" ]
    command: [ "-A", "server.celery", "worker", "--loglevel=info" ]
    volumes:
      - ./api:/app
    links:
      - redis
    depends_on:
      - redis
