version: '3.8'

services:

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    hostname: redis

  worker:
    container_name: celeryserver
    build:
      context: .  # Adjusted to current directory
    hostname: worker
    entrypoint: celery
    command: -A app.server.celery worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis
